app/models.py
from app import db


class Student(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    student_ref = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text, nullable=False)
    email = db.Column(db.Text)
    password = db.Column(db.Text)
    grades = db.relationship('Grade', backref='students')

    def __repr__(self):
        return '<Student {}>'.format(self.student_id)


class Teacher(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher_ref = db.Column(db.Text, nullable=False)
    title = db.Column(db.Text)
    name = db.Column(db.Text)
    courses = db.relationship('Course', backref='teachers')

    def __repr__(self):
        return '<Teacher {} {}>'.format(self.first_name, self.last_name)


class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_code = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text, nullable=False)
    teacher_id = db.Column(db.Integer, db.ForeignKey('teacher.id'), nullable=False)
    grades = db.relationship('Grade', backref='courses')

    def __repr__(self):
        return '<Course {}>'.format(self.code, self.name)


class Grade(db.Model):
    student_id = db.Column(db.Integer, db.ForeignKey('student.id'), nullable=False, primary_key=True)
    course_id = db.Column(db.Integer, db.ForeignKey('course.id'), nullable=False, primary_key=True)
    grade = db.Column(db.Text)

    def __repr__(self):
        return '<Grade {}>'.format(self.grade)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email


class SignupForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email address', validators=[DataRequired(), Email(message='Valid email address required')])
    password = PasswordField('Password',
                             validators=[DataRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Repeat Password')
    submit = SubmitField('Sign Up')

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

from config import DevConfig

# The SQLAlchemy object is defined globally
db = SQLAlchemy()


def page_not_found(e):
    return render_template('404.html'), 404


def internal_server_error(e):
    return render_template('500.html'), 500


def create_app(config_class=DevConfig):
    """
    Creates an application instance to run
    :return: A Flask object
    """
    app = Flask(__name__)

    # Configure app wth the settings from config.py
    app.config.from_object(config_class)

    # Initialise the database and create tables
    db.init_app(app)
    from app.models import Teacher, Student, Course, Grade
    with app.app_context():
        db.create_all()

    # Register error handlers
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    # Register Blueprints
    from app.main.routes import bp_main
    app.register_blueprint(bp_main)

    return app

app/main/routes.py
from flask import render_template, Blueprint, request, flash, redirect, url_for

from app.main.forms import SignupForm

bp_main = Blueprint('main', __name__)


@bp_main.route('/')
def index():
    return render_template('index.html', name="world")


@bp_main.route('/signup/', methods=['POST', 'GET'])
def signup():
    form = SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        flash('Signup requested for {}'.format(form.name.data))
        # Code to add the student to the database goes here
        return redirect(url_for('main.index'))
    return render_template('signup.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {#  Allows each page title to be set using a variable named 'title' #}
        {% block title %}{{ title }}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.signup') }}">Sign up</a>
        </li>
    </ul>
</nav>
<div role=main class="container-fluid">
    <!-- Displays flashed messages on a page -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    
    {% endif %}
    {% endwith %}
    <!-- Child pages add page specific content here -->
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

app/templates/form_example.html
<!-- Use the base template -->
{% extends "base.html" %}

<!-- Title for this page -->
{% block title %} Login {% endblock %}

<!-- Content for this page -->
{% block content %}
    <br>
    <div class="card col-md-3">
        <form>
            <legend class="form-text">Login</legend>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                       placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="rememberMe">
                <label class="form-check-label" for="rememberMe">Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary form-group">Submit</button>
        </form>
    </div>
{% endblock %}

app/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">Hello</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Hi</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Hola</a>
        </li>
    </ul>
</nav>
<div class="container-fluid">
    <h1>Hello, {{ name }}</h1>
</div>
</body>
</html>

app/templates/hello_child.html
<!-- Use the base template -->
{% extends "base.html" %}

<!-- Title for this page -->
{% block title %} Hello {% endblock %}

<!-- Content for this page -->
{% block content %}
    <h1>Hello, {{ name }}</h1>
{% endblock %}

app/templates/index.html
<!-- Use the base template -->
{% extends "base.html" %}

<!-- Title for this page -->
{% block title %} Hello {% endblock %}

<!-- Content for this page -->
{% block content %}
    <h1>Hello, {{ name }}</h1>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %} Signup {% endblock %}
{% block content %}
<br>
{# Display the form validation errors #}
{% if form.errors %}
    <p><strong>The form contains errors:</strong>
    <ul>
        {% for error in form.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>{{ form.name.label }}<br>{{ form.name(size=32) }}</p>
    <p>{{ form.email.label }}<br>{{ form.email(size=32) }}</p>
    <p>{{ form.password.label }}<br>{{ form.password }}</p>
    <p>{{ form.confirm.label }}<br>{{ form.confirm }}</p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}